#!/usr/bin/python3
def raise_exception_msg(message=""):
    """Raises a NameError with a specified message.

    Args:
    message: The message to be associated with the NameError exception.
    """
    raise NameError(message)
